name: Build and Release Content

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Clear dist folder
        run: |
          rm -rf docs/.vitepress/dist/
      - name: Install and build
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          npm install
          npm run docs:build
          envsubst < "typesense-scraper.env" > "typesense-scraper-updated.env"
          docker run -i -d -p 8080:8080 -v ${GITHUB_WORKSPACE}/docs/.vitepress/dist:/public danjellz/http-server
          echo "local http server running..."
          docker run -d -p 8108:8108 -v ${GITHUB_WORKSPACE}/typesense-data/data/:/data typesense/typesense:0.21.0 --data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors &
          sleep 5
          docker run -i --env-file typesense-scraper-updated.env -e "CONFIG=$(cat typesense-scraper-config.json | jq -r tostring)" typesense/docsearch-scraper
          cd /tmp/typesense-data && ls -l
          curl 'http://172.17.0.3:8108/keys' -X POST -H "X-TYPESENSE-API-KEY: ${TYPESENSE_API_KEY}" -H 'Content-Type: application/json' -d '{"value": "N4N8bF0XwyvzwCGwm3CKB0QcnwyWtygo","description": "Search only","actions": ["documents:search"],"collections":["*"]}'
          cd ${GITHUB_WORKSPACE}/typesense-data
          docker build . -t servicestack-search
      - name: Deploy to GitHub Pages
        run: |
          cd docs/.vitepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/.vitepress/dist

