name: Build and Release Content

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Clear dist folder
        run: |
          rm -rf docs/.vitepress/dist/
      - name: Install and build
        run: |
          npm install
          npm run docs:build
          npm install http-server -g
          cd docs/.vitepress/dist
          http-server &
          sleep 5
          echo "local http server running..."
          docker run -p 8108:8108 -v /tmp/typesense-data/:/data typesense/typesense:0.21.0 --data-dir /data --api-key=testtest --enable-cors
          sleep 5
      - name: Run typesense scrape
        uses: docker://typesense/docsearch-scraper:latest
        env: 
          TYPESENSE_API_KEY: testtest
          TYPESENSE_HOST: 172.17.0.2
          TYPESENSE_PORT: 8108
          TYPESENSE_PROTOCOL: http
          CONFIG: '{"index_name":"typesense_docs","start_urls":[{"url":"http://127.0.0.1:8080/"}],"selectors":{"default":{"lvl0":".content h1","lvl1":".content h2","lvl2":".content h3","lvl3":".content h4","lvl4":".content h5","text":".content p, .content ul li, .content table tbody tr"}},"scrape_start_urls":false,"strip_chars":" .,;:#"}'
      - name: Deploy to GitHub Pages
        run: |
          cd docs/.vitepress/dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/.vitepress/dist

